#!/bin/bash

if [ $# -ne 4 ]; then
    echo "Usage: $0 ISIS_VERSION XSL_FILE COOKIES_FILE COURSE_NUMBER"
    exit 1
fi

if [ "$1" = "1" ]; then
    URL="https://isis.tu-berlin.de/archiv/course/view.php?id=$4"
    PDF_ICON="pdf.gif"
elif [ "$1" = "2" ]; then
    URL="https://isis.tu-berlin.de/course/view.php?id=$4"
    PDF_ICON="pdf-24"
else 
    echo -e "\033[41mFalscher Parameter:\033[0m ISIS-Version muss 1 oder 2 sein."
    exit 1
fi
XSL="$2"
COOKIES="$3"

if [ "$(which wget 2>/dev/null)" != "" ]; then
    DL="wget"
    DL_SILENT="-q"
    DL_COOKIES="--load-cookies"
    DL_OUTPUT="-O"
elif [ "$(which curl 2>/dev/null)" != "" ]; then
    DL="curl"
    DL_SILENT="-s"
    DL_COOKIES="-b"
    DL_OUTPUT="-o"
else
    echo -e "\033[41mUnerfüllte Voraussetzung:\033[0m Weder curl noch wget wurden gefunden. Abbruch."
    exit 1
fi

# Download course page
$DL $DL_SILENT $DL_COOKIES "$COOKIES" $DL_OUTPUT "/tmp/$$.html" "$URL"
# Get the files
xsltproc -html "$XSL" "/tmp/$$.html" 2>/dev/null | while read url img name; do
    if [ "$img" = "" -o "$name" = "" ]; then
        echo -e "\033[41mIgnoriert (Typ/Name unbekannt):\033[0m $url"
    else
        type="`basename "$img"`"

        case $type in
	    $PDF_ICON)
	        filename="$(echo $name | sed "y/\//_/").pdf"
	        echo -e "\033[42mPDF:\033[0m $filename"
	        $DL $DL_SILENT $DL_COOKIES "$COOKIES" $DL_OUTPUT "$filename" "$url"
	        ;;
            *)
	        filename="$(echo $name | sed "y/\//_/")"
                echo -e "\033[41mIgnoriert (Kein PDF):\033[0m $filename"
                ;;
        esac
    fi
done

